name: Build QtApng
on:
  push:
  pull_request:
  workflow_dispatch:

env:
  MACOSX_DEPLOYMENT_TARGET: 10.15

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            vers: '5.15.2'
          - os: ubuntu-latest
            vers: '6.8.2'
          - os: macos-13
            vers: '5.15.2'
          - os: macos-13
            vers: '6.8.2'
            buildArch: 'Universal'
          - os: windows-2019
            vers: '5.15.2'
            arch: 'win32_msvc2019'
            buildArch: 'X86'
          - os: windows-2019
            vers: '5.15.2'
            arch: 'win64_msvc2019_64'
          - os: windows-2022
            vers: '6.8.2'
            arch: 'win64_msvc2022_64'
          - os: windows-2022
            vers: '6.8.2'
            arch: 'win64_msvc2022_arm64_cross_compiled'
            buildArch: 'Arm64'

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          cache: true
          version: ${{ matrix.vers }}
          arch: ${{ matrix.arch }}

      - name: Build QtApng
        run: pwsh pwsh/buildapng.ps1
        env:
          buildArch: ${{ matrix.buildArch }}

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: qtapng-${{ matrix.os }}-${{ matrix.vers }}${{ matrix.arch && format('-{0}', matrix.arch) || '' }}
          path: QtApng/output
